Feature - Update Find command
AY2122S2-CS2103-W16-2/tp pull request #76
Opened 2022-03-10 14:25 UTC by zihaowrez

This commit fixes issue #68

2022-03-11 06:48 UTC, cheehongw reviewed
Seems now the `Find` command will match keywords in both `name` and `Tags`, but is it possible or easy to extend the code for it to find a user given a matching phone number or any attribute of `Person`?

2022-03-14 12:13 UTC, cheehongw approved these changes
LGTM

2022-03-14 12:35 UTC, reignnz requested changes
Other than that looks good to me!

2022-03-14 12:35 UTC, reignnz commented on src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java
> +        if (keywords.stream()
Is it possible to abstract out the conditional statements into separate methods such that each one tests for name, phone, etc?

2022-03-14 13:56 UTC, merged